name: cOS bump
on: 
 schedule:
   - cron: 0 20 * * *
 push:
    branches: [ test_auto ]
 workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Bump cos 🔧
      run: |
           docker run --name=yq -v "${PWD}":/workdir mikefarah/yq
           docker cp yq:/usr/bin/yq ./
           export YQ=$PWD/yq
           sudo -E bash ./.github/bump_cos.sh
           rm -rf yq
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.PAT_TOKEN }}
        push-to-fork: ci-robbot/c3os
        commit-message: ":arrow_up: Bump cOS"
        title: "cOS bump"
        body: "Bump of cOS repositories"
